//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 12:31:29 PM IST 
//


package com.admin.rs.config.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.admin.rs.config.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.admin.rs.config.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveProgramRequest }
     * 
     */
    public SaveProgramRequest createSaveProgramRequest() {
        return new SaveProgramRequest();
    }

    /**
     * Create an instance of {@link GetAllProgramsRequest }
     * 
     */
    public GetAllProgramsRequest createGetAllProgramsRequest() {
        return new GetAllProgramsRequest();
    }

    /**
     * Create an instance of {@link GetAllProgramsResponse }
     * 
     */
    public GetAllProgramsResponse createGetAllProgramsResponse() {
        return new GetAllProgramsResponse();
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram() {
        return new Program();
    }

    /**
     * Create an instance of {@link GetProgramRequest }
     * 
     */
    public GetProgramRequest createGetProgramRequest() {
        return new GetProgramRequest();
    }

    /**
     * Create an instance of {@link GetProgramResponse }
     * 
     */
    public GetProgramResponse createGetProgramResponse() {
        return new GetProgramResponse();
    }

    /**
     * Create an instance of {@link UpdateProgramRequest }
     * 
     */
    public UpdateProgramRequest createUpdateProgramRequest() {
        return new UpdateProgramRequest();
    }

    /**
     * Create an instance of {@link DeleteProgramRequest }
     * 
     */
    public DeleteProgramRequest createDeleteProgramRequest() {
        return new DeleteProgramRequest();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

}
